# Auto-generated by LSTL_GeneratePython — do not edit.
from ._prim import int32
from ._runtime import BoundArray
from ._runtime import BoundObject

class int2(BoundObject):
    @property
    def vec(self) -> BoundArray[int32]: ...

class float3(BoundObject):
    @property
    def vec(self) -> BoundArray[float]: ...

class AABB_float3(BoundObject):
    @property
    def min(self) -> float3: ...
    @property
    def max(self) -> float3: ...

class float4(BoundObject):
    @property
    def vec(self) -> BoundArray[float]: ...

class float2(BoundObject):
    @property
    def vec(self) -> BoundArray[float]: ...

class int4(BoundObject):
    @property
    def vec(self) -> BoundArray[int32]: ...
