# Auto-generated by LSTL_GeneratePython — do not edit.
from ._runtime import BoundObject
from enum import IntEnum

class Prop(IntEnum):
    INVALID_TYPE = -1
    FLOAT32 = 0
    FLOAT64 = 1
    INT64 = 2
    UINT64 = 3
    INT32 = 4
    UINT32 = 5
    INT16 = 6
    UINT16 = 7
    INT8 = 8
    UINT8 = 9
    BOOL = 10
    STRING = 11
    STATIC_STRING = 12
    LIST = 13
    STRUCT = 14

class StructProp(BoundObject):
    type: Prop
    @property
    def name(self) -> str: ...
    @property
    def ui_name(self) -> str: ...
    def lookupFloat(self, name: str, default_value: float) -> float: ...
