# Auto-generated by LSTL_GeneratePython — do not edit.
from ._runtime import BoundObject
from .sculptcore_gpu import DrawBatch
from .sculptcore_gpu import GPUManager
from .sculptcore_mesh import Mesh

class MeshBatchManager(BoundObject):
    m: Mesh
    def createMeshBatch(self, gpuManager: GPUManager) -> DrawBatch | None: ...
