# SPDX-FileCopyrightText: 2026 Blender Authors
# SPDX-License-Identifier: GPL-2.0-or-later
"""Freeze reviewed numeric native metadata without importing Blender or the engine."""
import hashlib
import json
from pathlib import Path
import pprint
import sys
import textwrap

ROOT = Path(__file__).resolve().parents[2]
source = ROOT / 'claudeMemory/design/generic-brush-inventory-v1.json'
rows = json.loads(source.read_text(encoding='utf-8'))['rows']
paths = ('size', 'unprojected_size', 'spacing', 'plane_offset', 'crease_pinch_factor', 'hardness',
         'auto_smooth_factor', 'use_accumulate', 'use_space_attenuation', 'use_original_normal',
         'use_original_plane', 'normal_radius_factor', 'area_radius_factor', 'stabilize_normal',
         'stabilize_plane')
dynamic = {'spacing', 'plane_offset', 'crease_pinch_factor', 'auto_smooth_factor'}
selected = [r for r in rows if r['path'] in ('Brush.' + p for p in paths)
            or (r['path'].startswith('Brush.mesh_automasking_settings.')
                and r['stable_ids'] and r['metadata']['type'] in ('INT', 'FLOAT', 'BOOLEAN'))]
output = ['# SPDX-FileCopyrightText: 2026 Blender Authors', '# SPDX-License-Identifier: GPL-2.0-or-later',
          '"""Generated by generate_native_authoring.py from the reviewed migration inventory."""',
          'SOURCE_SHA256 = ' + repr(hashlib.sha256(source.read_bytes()).hexdigest()), 'ROWS = (']
for row in selected:
    m = row['metadata']
    path = row['path'].removeprefix('Brush.')
    kind = {'INT': 'INT32', 'FLOAT': 'FLOAT32', 'BOOLEAN': 'BOOL'}[m['type']]
    bounds = (0, 1, 0, 1) if kind == 'BOOL' else (m['hard_min'], m['hard_max'], m['soft_min'], m['soft_max'])
    item = (row['stable_ids'][0], path, kind, m['default'], *bounds, m['description'], path in dynamic)
    output.append(textwrap.indent(pprint.pformat(item, width=116), '    ') + ',')
output.append(')')
destination = ROOT / 'sculptcore_addon/brush_properties/native_v0.py'
generated = '\n'.join(output) + '\n'
if '--check' in sys.argv:
    assert destination.read_text(encoding='utf-8') == generated, 'Frozen native inventory needs regeneration'
else:
    destination.write_text(generated, encoding='utf-8')
print('NATIVE_AUTHORING_GENERATED_OK', len(selected))
