# SPDX-FileCopyrightText: 2026 Blender Authors
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate DLL-independent Plan 1 legacy definitions; --check verifies provenance."""
import hashlib
import json
from pathlib import Path
import pprint
import sys

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'claudeMemory/tests/generic-brush-v0'
baseline = json.loads((BASE / 'baseline.json').read_text(encoding='utf-8'))
rna = json.loads((BASE / 'registered-rna.json').read_text(encoding='utf-8'))
sources = {'BSMOOTH': ('engine/source/brush/kernels/bsmooth.sbrush', False),
           'CLAY': ('engine/source/brush/kernels/plane.sbrush', False),
           'FILL': ('engine/source/brush/kernels/plane.sbrush', False),
           'SCRAPE': ('engine/source/brush/kernels/plane.sbrush', False),
           'NUDGE': ('brushes/nudge.sbrush', False),
           'KELVINLET': ('engine/source/brush/kernels/kelvinlet.sbrush', True)}
rows = []
for kernel, entries in sorted(baseline['manifests'].items()):
    for name, *_ in entries:
        metadata = rna[name]
        assert metadata['type'] == 'FLOAT'
        rows.append((f'sculptcore.kernel.{kernel.lower()}.{name}', kernel, name,
                     metadata['default'], metadata['hard_min'], metadata['hard_max'],
                     metadata['soft_min'], metadata['soft_max'], metadata['description'], metadata['unit'],
                     sources[kernel][1]))
assert len(rows) == 7 and len({row[2] for row in rows}) == 5
paths = ['claudeMemory/tests/generic-brush-v0/baseline.json',
         'claudeMemory/tests/generic-brush-v0/registered-rna.json',
         'claudeMemory/tests/generic-brush-v0/runtime.json'] + sorted({item[0] for item in sources.values()})
hashes = tuple((path, hashlib.sha256((ROOT / path).read_bytes()).hexdigest()) for path in paths)
content = '''# SPDX-FileCopyrightText: 2026 Blender Authors
# SPDX-License-Identifier: GPL-2.0-or-later
"""Frozen v0 defaults and associations; generated by generate_frozen_authoring.py.

Rows: stable ID, kernel, legacy name, default, hard min/max, soft min/max,
description, unit, dynamic. Slots are intentionally excluded.
"""

'''
content += 'SOURCE_HASHES = ' + pprint.pformat(hashes, width=118) + '\n\n'
content += 'LEGACY_ROWS = ' + pprint.pformat(tuple(rows), width=118) + '\n'
target = ROOT / 'sculptcore_addon/brush_properties/frozen_v0.py'
if '--check' in sys.argv:
    assert target.read_text(encoding='utf-8') == content, 'Frozen catalogue differs from reviewed inputs'
else:
    target.write_text(content, encoding='utf-8', newline='\n')
print('FROZEN_GENERATION_OK', len(rows))
