# SPDX-FileCopyrightText: 2026 Blender Authors
# SPDX-License-Identifier: GPL-2.0-or-later
from pathlib import Path
for file in ['engine/source/brush/brush_executor.h','engine/source/brush/grid_executor.h']:
 p=Path(file);s=p.read_text();s=s.replace('applyResolvedDab(SculptBrushes brushType, float3 center, float3 normal);','applyResolvedDab(SculptBrushes brushType, float3 center, float3 normal, bool validateOnly = false);').replace('applyResolvedDab(SculptBrushes brushType, float3 origin, float3 normal);','applyResolvedDab(SculptBrushes brushType, float3 origin, float3 normal, bool validateOnly = false);').replace('applyResolvedProgram(BrushProgram *program, float3 center, float3 normal);','applyResolvedProgram(BrushProgram *program, float3 center, float3 normal, bool validateOnly = false);').replace('applyResolvedProgram(BrushProgram *program, float3 origin, float3 normal);','applyResolvedProgram(BrushProgram *program, float3 origin, float3 normal, bool validateOnly = false);');p.write_text(s)
for file in ['engine/source/brush/brush_executor.cc','engine/source/brush/grid_executor.cc']:
 p=Path(file);s=p.read_text();s=s.replace('applyResolvedDab(SculptBrushes brushType, float3 center, float3 normal)','applyResolvedDab(SculptBrushes brushType, float3 center, float3 normal, bool validateOnly)').replace('applyResolvedDab(SculptBrushes brushType, float3 origin, float3 normal)','applyResolvedDab(SculptBrushes brushType, float3 origin, float3 normal, bool validateOnly)').replace('applyResolvedProgram(BrushProgram *program, float3 center, float3 normal)','applyResolvedProgram(BrushProgram *program, float3 center, float3 normal, bool validateOnly)').replace('BrushProgram *program, float3 origin, float3 normal)\n{','BrushProgram *program, float3 origin, float3 normal, bool validateOnly)\n{');s=s.replace('  lastRegistration = prepared.publish(*brush);','  if (validateOnly)\n    return {};\n  lastRegistration = prepared.publish(*brush);');a=s.index('applyResolvedProgram(');first=s[:a];s=s[a:];s=s.replace('    if (lastRegistration.error != PropError::ERROR_NONE)\n      return lastRegistration;','    if (lastRegistration.error != PropError::ERROR_NONE || validateOnly)\n      return lastRegistration;',1);needle='  if (lastRegistration.error != PropError::ERROR_NONE)\n    return lastRegistration;';# after prepareProgramScalars, not resolvedState
 idx=s.index('  lastRegistration = prepareProgramScalars(');tail=s[idx:];tail=tail.replace(needle,'  if (lastRegistration.error != PropError::ERROR_NONE || validateOnly)\n    return lastRegistration;',1);s=s[:idx]+tail;p.write_text(first+s)
p=Path('engine/source/brush/c-api/dab_inputs.h');s=p.read_text().replace('property(const char *name)','property(const char *name, props::Prop type)').replace('p->type != P::Type','p->type != type').replace('property<props::Float32Prop>("radius")','property<props::Float32Prop>("radius", props::Prop::FLOAT32)').replace('property<props::Float32Prop>("strength")','property<props::Float32Prop>("strength", props::Prop::FLOAT32)').replace('property<props::BoolProp>("invert")','property<props::BoolProp>("invert", props::Prop::BOOL)').replace('(typed->binding_offset != -1 && brush_.props.owner)','(typed->binding_offset != -1 && (typed->owner || brush_.props.owner)) ||\n        (typed->flag & props::PropFlag::READ_ONLY) != props::PropFlag::NONE');p.write_text(s)
for file in ['engine/source/brush/c-api/mesh_stroke_batch_c_api.cc','engine/source/brush/c-api/grid_stroke_c_api.cc']:
 p=Path(file);s=p.read_text();needle='    brush::setDabInputs(';idx=s.index(needle);s=s[:idx]+('    brush::DabInputOverlay overlay(*brush);\n' if 'mesh_' in file else '    brush::DabInputOverlay overlay(*s->exec.brush);\n')+'    if (!overlay.valid())\n      return -1;\n'+s[idx:];idx=s.index('    brush::setDabInputs(');end=s.index('  return total;',idx);part=s[idx:end];pos=part.rfind('  }');part=part[:pos]+'    overlay.commit();\n'+part[pos:];s=s[:idx]+part+s[end:];p.write_text(s)
