# Auto-generated by LSTL_GeneratePython — do not edit.
# Width-named integer aliases so signatures mirror the C++ declarations.

int8 = int
uint8 = int
int16 = int
uint16 = int
int32 = int
uint32 = int
int64 = int
uint64 = int
# Raw void* crossing the ABI as an integer address (Binder<void*>).
pointer = int
