// AUTO-GENERATED by sbrushc --registry — DO NOT EDIT.
// Extra-kernel registry: factory dispatch + metadata for kernels compiled
// from SCULPTCORE_EXTRA_KERNEL_DIRS. Consumed via brushes/extra.h; the
// matching enum items live in sculptcore_extra_brushes_enum.inc.
#pragma once
#include "brush/brush_command.h"
#include "brush/brushes/types.h"
#include "brush/neighbor_source.h"

namespace sculptcore::brush {

inline constexpr int extraNamedFloatCount = 1;
inline constexpr int kExtraSlot_typed_gain = 0;
inline constexpr float kExtraNamedFloatDefaults[] = {0.25f};
inline constexpr NamedUniformDescriptor kExtraNamedFloatDescriptors[] = {
  {"typed_gain", props::Prop::FLOAT32, true},
};
inline constexpr int extraNamedIntCount = 5;
inline constexpr int kExtraSlot_typed_count = 0;
inline constexpr int kExtraSlot_typed_low = 1;
inline constexpr int kExtraSlot_typed_high = 2;
inline constexpr int kExtraSlot_typed_limited = 3;
inline constexpr int kExtraSlot_typed_work = 4;
inline constexpr int32_t kExtraNamedIntDefaults[] = {16777217, -2147483648, 2147483647, 2, 16777217};
inline constexpr NamedUniformDescriptor kExtraNamedIntDescriptors[] = {
  {"typed_count", props::Prop::INT32, true},
  {"typed_low", props::Prop::INT32, false},
  {"typed_high", props::Prop::INT32, false},
  {"typed_limited", props::Prop::INT32, false},
  {"typed_work", props::Prop::INT32, false},
};
inline constexpr int extraNamedBoolCount = 3;
inline constexpr int kExtraSlot_typed_enabled = 0;
inline constexpr int kExtraSlot_typed_static = 1;
inline constexpr int kExtraSlot_typed_gate = 2;
inline constexpr bool kExtraNamedBoolDefaults[] = {true, true, true};
inline constexpr NamedUniformDescriptor kExtraNamedBoolDescriptors[] = {
  {"typed_enabled", props::Prop::BOOL, true},
  {"typed_static", props::Prop::BOOL, false},
  {"typed_gate", props::Prop::BOOL, false},
};

inline const NamedUniformDescriptor *generatedExtraNamedUniformDescriptor(props::Prop type, int slot)
{
  (void)type; (void)slot;
  if (type == props::Prop::FLOAT32 && slot >= 0 && slot < extraNamedFloatCount) {
    return &kExtraNamedFloatDescriptors[slot];
  }
  if (type == props::Prop::INT32 && slot >= 0 && slot < extraNamedIntCount) {
    return &kExtraNamedIntDescriptors[slot];
  }
  if (type == props::Prop::BOOL && slot >= 0 && slot < extraNamedBoolCount) {
    return &kExtraNamedBoolDescriptors[slot];
  }
  return nullptr;
}

/** Initialize untouched slots, preserving every existing working value. */
inline void ensureExtraUniformDefaults(Brush &b)
{
  (void)b;
  for (int i = 0; i < extraNamedFloatCount; i++) {
    b.ensureNamedFloatDefault(i, kExtraNamedFloatDefaults[i]);
  }
  for (int i = 0; i < extraNamedIntCount; i++) {
    b.ensureNamedIntDefault(i, kExtraNamedIntDefaults[i]);
  }
  for (int i = 0; i < extraNamedBoolCount; i++) {
    b.ensureNamedBoolDefault(i, kExtraNamedBoolDefaults[i]);
  }
}

} // namespace sculptcore::brush

#include "typed_probe.brush.gen.h"
#include "typed_peer.brush.gen.h"

namespace sculptcore::brush {

inline constexpr int extraBrushCount = 2;

inline bool extraBrushUsesForNeighbor(int id)
{
  (void)id;
  return false;
}

/** `@fulltopo`: the kernel or its host pre-pass walks live topology links
 * every dab, so the stroke must not freeze topology. */
inline bool extraBrushFullTopo(int id)
{
  (void)id;
  return false;
}

/** The kernel has a `face` stage, so it is dispatched per face and reaches
 * its verts through the live face loop. */
inline bool extraBrushFaceMode(int id)
{
  (void)id;
  return false;
}

} // namespace sculptcore::brush

namespace sculptcore::brush::command {

/** Dispatch an extra-brush id to its generated factory. Returns false when
 * `id` is not an extra brush (the caller falls through to its own error
 * path). The neighbor sources and the face-stage guard follow
 * createBuiltinBrush exactly, so an extra kernel is admitted on every
 * domain its own annotations allow; the named-float store is sized +
 * default-seeded per command creation. */
template <CommandTypes TYPES,
          sculptcore::brush::NbrSource NbrCsr,
          sculptcore::brush::NbrSource NbrLive,
          sculptcore::brush::AccumMode AccMode>
inline bool createExtraBrush(int id, bool csrNeighbors, sculptcore::brush::Brush &brush,
                             BrushCommandDef<CommandCtx<TYPES>> &def)
{
  (void)csrNeighbors;
  ensureExtraUniformDefaults(brush);
  switch (id - SculptBrushesBuiltinCount) {
  case 0: // typed_probe
    createTypedprobeBrush<TYPES, AccMode>(def);
    return true;
  case 1: // typed_peer
    createTypedpeerBrush<TYPES, AccMode>(def);
    return true;
  default:
    return false;
  }
}

} // namespace sculptcore::brush::command
