# Auto-generated by LSTL_GeneratePython — do not edit.
from ._prim import int32
from ._prim import pointer
from ._prim import uint32
from ._prim import uint8
from ._runtime import BoundObject
from ._runtime import BoundVector
from .litestl_math import float2
from .litestl_math import float3
from enum import IntEnum
from typing import TypeAlias

class GPUBufferType(IntEnum):
    BUFFER_ARRAY = 0
    BUFFER_INDEX = 1
    BUFFER_TEXTURE = 2
    BUFFER_UNIFORM = 3

class FalloffShape(IntEnum):
    SPHERICAL = 0
    CUBE = 1
    LINEAR = 2
    BOX = 3

class GPUType(IntEnum):
    TYPE_INVALID = -1
    FLOAT16 = 0
    FLOAT32 = 1
    FLOAT64 = 2
    INT32 = 3
    INT16 = 4
    INT8 = 5
    UINT32 = 6
    UINT16 = 7
    UINT8 = 8

class UniformBindType(IntEnum):
    FLOAT = 0
    DOUBLE = 1
    BYTE = 2
    UBYTE = 3
    SHORT = 4
    USHORT = 5
    INT = 6
    UINT = 7
    FLOAT2 = 8
    FLOAT3 = 9
    FLOAT4 = 10
    INT2 = 11
    INT3 = 12
    INT4 = 13
    UINT2 = 14
    UINT3 = 15
    UINT4 = 16
    DOUBLE2 = 17
    DOUBLE3 = 18
    DOUBLE4 = 19
    SHORT2 = 20
    SHORT3 = 21
    SHORT4 = 22
    USHORT2 = 23
    USHORT3 = 24
    USHORT4 = 25
    BYTE2 = 26
    BYTE3 = 27
    BYTE4 = 28
    UBYTE2 = 29
    UBYTE3 = 30
    UBYTE4 = 31

class FalloffKind(IntEnum):
    LINEAR = 1
    SMOOTHSTEP = 0
    GUASSIAN = 2
    CURVE = 3

class GPUFetchMode(IntEnum):
    FETCH_NONE = 0
    FETCH_FLOAT = 1

class GPUCmdType(IntEnum):
    DRAW_TRIS = 0
    DRAW_TRI_STRIP = 1
    DRAW_LINES = 2
    DRAW_POINTS = 3

class Buffer(BoundObject):
    @property
    def name(self) -> str: ...
    type: GPUType
    size: int32
    elemsize: int32
    mode: GPUFetchMode
    target: GPUBufferType
    data: pointer
    update_buffer: bool
    update_start: int32
    update_end: int32
    def resize(self, size: int32) -> None: ...
    def dirty(self) -> None: ...

class DrawPipeline(BoundObject):
    @property
    def batches(self) -> BoundVector[DrawBatch]: ...
    @property
    def blocks(self) -> BoundVector[UniformBlockInstance]: ...

class UniformDef_float3(BoundObject):
    @property
    def name(self) -> str: ...
    type: GPUType
    elemSize: int32
    @property
    def defaultValue(self) -> float3: ...

class AttrDef(BoundObject):
    @property
    def name(self) -> str: ...
    type: GPUType
    elemSize: int32

class DrawCommand(BoundObject):
    type: GPUCmdType
    shader: ShaderDef | None
    @property
    def attrs(self) -> BoundVector[Buffer]: ...
    start: int32
    end: int32
    primCount: int32
    @property
    def blocks(self) -> BoundVector[UniformBlockInstance]: ...

class UniformBlockInstance(BoundObject):
    def_: UniformBlockDef | None
    @property
    def data(self) -> BoundVector[uint8]: ...

class GPUManager(BoundObject):
    @property
    def buffers(self) -> BoundVector[Buffer]: ...
    @property
    def batches(self) -> BoundVector[DrawBatch]: ...
    @property
    def commands(self) -> BoundVector[DrawCommand]: ...
    def createBuffer(self, name: str, type: GPUType, elemsize: int32, elemCount: int32) -> Buffer: ...
    def createBatch(self) -> DrawBatch: ...
    def createCommand(self, batch: DrawBatch, type: GPUCmdType, shader: ShaderDef | None, start: int32, end: int32, primCount: int32) -> DrawCommand: ...
    def destroyBatch(self, batch: DrawBatch, destroy_commands: bool, destroy_buffers: bool) -> None: ...
    def destroyBuffer(self, buffer: Buffer) -> None: ...
    def destroyCommand(self, command: DrawCommand, destroy_buffers: bool) -> None: ...

class UniformBlockDef(BoundObject):
    @property
    def name(self) -> str: ...
    @property
    def fields(self) -> BoundVector[UniformBindTypeMap]: ...
    set: uint32
    binding: uint32
    packedBytes: uint32
    preferPushConstant: bool

class DrawBatch(BoundObject):
    @property
    def commands(self) -> BoundVector[DrawCommand]: ...
    @property
    def buffers(self) -> BoundVector[Buffer]: ...
    id: int32
    version: int32
    @property
    def cmdAabbs(self) -> BoundVector[float]: ...
    aabbVersion: int32
    @property
    def blocks(self) -> BoundVector[UniformBlockInstance]: ...

class UniformDef_float(BoundObject):
    @property
    def name(self) -> str: ...
    type: GPUType
    elemSize: int32
    defaultValue: float

class ShaderDef(BoundObject):
    @property
    def name(self) -> str: ...
    @property
    def wgslSource(self) -> str: ...
    @property
    def attrs(self) -> BoundVector[AttrDef]: ...
    @property
    def uniforms(self) -> BoundVector[UniformBlockDef]: ...

class UniformDef_float2(BoundObject):
    @property
    def name(self) -> str: ...
    type: GPUType
    elemSize: int32
    @property
    def defaultValue(self) -> float2: ...

UniformBindTypeMap: TypeAlias = UniformDef_float | UniformDef_float2 | UniformDef_float3
