# Auto-generated by LSTL_GeneratePython — do not edit.
from ._prim import int32
from ._prim import uint32
from ._runtime import BoundObject

class RemeshParams(BoundObject):
    target_quad_count: int32
    target_edge_length: float
    use_curvature: bool
    use_sharp_features: bool
    sharp_angle: float
    feature_hysteresis: float
    feature_min_chain: int32
    use_density: bool
    quantize_direct_rounding: bool
    untangle_field_max_dev: float
    reproject: bool
    cap_odd_holes: bool
    smooth_iterations: int32
    smooth_strength: float
    seed: uint32
    triage: bool
    triage_weld_rel: float
    triage_min_component_frac: float
    input_hole_fill_max_frac: float
    per_component: bool
    curvature_smooth_iters: int32
    curvature_smooth_lambda: float
    field_smoothness: float
    curvature_weight: float
    singularity_cancel: bool
    singularity_cancel_max_sep: float
    auto_density: bool
    density_min: float
    density_max: float
    density_gradation: float
    density_gradation_iters: int32
    pre_remesh: bool
    pre_remesh_target: float
    pre_remesh_iters: int32
    pre_remesh_density: bool
    pre_remesh_gradation: float
    pre_remesh_gradation_iters: int32
    pre_remesh_align: float
    pre_remesh_field_cadence: int32
    pre_remesh_bootstrap_iters: int32
    pre_remesh_smooth_iters: int32
    pre_remesh_smooth_lambda: float
    pre_remesh_converge_eps: float
    pre_remesh_preserve_features: bool
    pre_remesh_sharp_angle: float
    pre_remesh_trace: bool
    pre_remesh_anchors: bool
    auto_retry: bool
    max_attempts: int32
    fast_decimate: bool
    fast_quantize: bool
